//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysArcos
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG
    {
        public int ID { get; set; }
        public System.DateTime DATA { get; set; }
        public string METODO { get; set; }
        public string DESCRICAO { get; set; }
    
        public virtual SISTEMA_ENTIDADE SISTEMA_ENTIDADE { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
